version: '3'
services:
  mongodb:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword

  mongo_init:
    image: mongo:4
    depends_on:
      - mongodb
    command: ["mongo", "--host", "mongodb", "-u", "admin", "-p", "secretpassword", "--authenticationDatabase", "admin", "/docker-entrypoint-initdb.d/init.js"]
    volumes:
      - ./resources/init.js:/docker-entrypoint-initdb.d/init.js

  test_runner:
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
      dockerfile: Dockerfile.testrunner
    depends_on:
      - mongo_init
    environment:
      - MONGO_CONSTR=mongodb://admin:secretpassword@mongodb:27017/admin
    networks:
      - test_network

networks:
  test_network:
    driver: bridge